
serve:
	@python manage.py runserver

requirements:
	@pip install -r ../requirements.txt

makemig:
	@python manage.py makemigrations

mig:
	@python manage.py migrate

sync:
	@python manage.py syncdb

static:
	@python manage.py collectstatic
